ignore:
  - "**/*.module.*"
  - "**/*initializer.*"
  - "**/*main.*"
  - "**/*.repository.*"
  - "**/mongoose-module-helper.ts"
  - "**/redis/connect.ts"
  - "**/redis.factory.ts"
  - "**/*.serializer.*"
  - "**/*.dto.*"
  - "**/resend.factory.ts"
  - "**/*.mock.*"

coverage:
  status:
    project: off
    patch: off
